
name: Simple build and deploy

on: [ workflow_dispatch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: setup jdk-17
        uses: actions/checkout@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn clean package 